# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_AimsQueueWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AimsQueueWidget(object):
    def setupUi(self, AimsQueueWidget):
        AimsQueueWidget.setObjectName("AimsQueueWidget")
        AimsQueueWidget.resize(661, 428)
        self.verticalLayout = QtWidgets.QVBoxLayout(AimsQueueWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(AimsQueueWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.uEditFeatureTab = EditFeatureWidget()
        self.uEditFeatureTab.setObjectName("uEditFeatureTab")
        self.tabWidget.addTab(self.uEditFeatureTab, "")
        self.uResolutionTab = ReviewQueueWidget()
        self.uResolutionTab.setObjectName("uResolutionTab")
        self.tabWidget.addTab(self.uResolutionTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.uMessageLabel = QtWidgets.QLabel(AimsQueueWidget)
        self.uMessageLabel.setText("")
        self.uMessageLabel.setObjectName("uMessageLabel")
        self.horizontalLayout_5.addWidget(self.uMessageLabel)
        self.horizontalLayout_5.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(AimsQueueWidget)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(AimsQueueWidget)

    def retranslateUi(self, AimsQueueWidget):
        _translate = QtCore.QCoreApplication.translate
        AimsQueueWidget.setWindowTitle(_translate("AimsQueueWidget", "Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.uEditFeatureTab), _translate("AimsQueueWidget", "Edit Feature"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.uResolutionTab), _translate("AimsQueueWidget", "Review"))
from EditFeatureWidget import EditFeatureWidget
from ReviewQueueWidget import ReviewQueueWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AimsQueueWidget = QtWidgets.QWidget()
    ui = Ui_AimsQueueWidget()
    ui.setupUi(AimsQueueWidget)
    AimsQueueWidget.show()
    sys.exit(app.exec_())
