# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_LineageDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LineageDialog(object):
    def setupUi(self, LineageDialog):
        LineageDialog.setObjectName("LineageDialog")
        LineageDialog.resize(621, 368)
        self.verticalLayout = QtWidgets.QVBoxLayout(LineageDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(LineageDialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.uSadListView = DictionaryListView(LineageDialog)
        self.uSadListView.setObjectName("uSadListView")
        self.verticalLayout.addWidget(self.uSadListView)
        self.label = QtWidgets.QLabel(LineageDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.uGroupDescription = QtWidgets.QTextEdit(LineageDialog)
        self.uGroupDescription.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.uGroupDescription.sizePolicy().hasHeightForWidth())
        self.uGroupDescription.setSizePolicy(sizePolicy)
        self.uGroupDescription.setMaximumSize(QtCore.QSize(16777215, 60))
        self.uGroupDescription.setObjectName("uGroupDescription")
        self.verticalLayout.addWidget(self.uGroupDescription)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(LineageDialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.uGroupId = QtWidgets.QLineEdit(LineageDialog)
        self.uGroupId.setObjectName("uGroupId")
        self.horizontalLayout.addWidget(self.uGroupId)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(LineageDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(LineageDialog)
        self.buttonBox.accepted.connect(LineageDialog.accept)
        self.buttonBox.rejected.connect(LineageDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(LineageDialog)

    def retranslateUi(self, LineageDialog):
        _translate = QtCore.QCoreApplication.translate
        LineageDialog.setWindowTitle(_translate("LineageDialog", "Refine group selection"))
        self.label_2.setText(_translate("LineageDialog", "Select freatures to add to Lineage Group"))
        self.label.setText(_translate("LineageDialog", "Provide A Group Description To Add Features To A New Group:"))
        self.label_3.setText(_translate("LineageDialog", "Or, Supply A Current Group Id To Add Feautres To An Existing Group:"))
from AimsUI.AimsClient.Gui.DictionaryList import DictionaryListView


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LineageDialog = QtWidgets.QDialog()
    ui = Ui_LineageDialog()
    ui.setupUi(LineageDialog)
    LineageDialog.show()
    sys.exit(app.exec_())
