# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AimsUI/AimsClient/Gui/Ui_NewAddressDialog.ui'
#
# Created: Fri Nov  6 14:38:35 2015
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_NewAddressDialog(object):
    def setupUi(self, NewAddressDialog):
        NewAddressDialog.setObjectName(_fromUtf8("NewAddressDialog"))
        NewAddressDialog.resize(386, 906)
        self.verticalLayout = QtGui.QVBoxLayout(NewAddressDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(NewAddressDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.uFullNum = QtGui.QLineEdit(NewAddressDialog)
        self.uFullNum.setMaximumSize(QtCore.QSize(200, 16777215))
        self.uFullNum.setObjectName(_fromUtf8("uFullNum"))
        self.horizontalLayout_2.addWidget(self.uFullNum)
        self.uAddressType = QtGui.QComboBox(NewAddressDialog)
        self.uAddressType.setObjectName(_fromUtf8("uAddressType"))
        self.horizontalLayout_2.addWidget(self.uAddressType)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_5 = QtGui.QLabel(NewAddressDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label_6 = QtGui.QLabel(NewAddressDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 4, 1, 1)
        self.label_8 = QtGui.QLabel(NewAddressDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 8, 1, 1)
        self.label_2 = QtGui.QLabel(NewAddressDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(NewAddressDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 6, 1, 1)
        self.uHigh = QtGui.QLineEdit(NewAddressDialog)
        self.uHigh.setMaximumSize(QtCore.QSize(65, 16777215))
        self.uHigh.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.uHigh.setObjectName(_fromUtf8("uHigh"))
        self.gridLayout.addWidget(self.uHigh, 1, 6, 1, 1)
        self.uBase = QtGui.QLineEdit(NewAddressDialog)
        self.uBase.setMaximumSize(QtCore.QSize(65, 16777215))
        self.uBase.setObjectName(_fromUtf8("uBase"))
        self.gridLayout.addWidget(self.uBase, 1, 4, 1, 1)
        self.uUnit = QtGui.QLineEdit(NewAddressDialog)
        self.uUnit.setMaximumSize(QtCore.QSize(65, 16777215))
        self.uUnit.setObjectName(_fromUtf8("uUnit"))
        self.gridLayout.addWidget(self.uUnit, 1, 2, 1, 1)
        self.uAlpha = QtGui.QLineEdit(NewAddressDialog)
        self.uAlpha.setMaximumSize(QtCore.QSize(65, 16777215))
        self.uAlpha.setObjectName(_fromUtf8("uAlpha"))
        self.gridLayout.addWidget(self.uAlpha, 1, 8, 1, 1)
        self.uPrefix = QtGui.QLineEdit(NewAddressDialog)
        self.uPrefix.setMaximumSize(QtCore.QSize(65, 16777215))
        self.uPrefix.setText(_fromUtf8(""))
        self.uPrefix.setObjectName(_fromUtf8("uPrefix"))
        self.gridLayout.addWidget(self.uPrefix, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line = QtGui.QFrame(NewAddressDialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_12 = QtGui.QLabel(NewAddressDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_12)
        self.externalAddressIdLabel = QtGui.QLabel(NewAddressDialog)
        self.externalAddressIdLabel.setObjectName(_fromUtf8("externalAddressIdLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.externalAddressIdLabel)
        self.uExternalAddId = QtGui.QLineEdit(NewAddressDialog)
        self.uExternalAddId.setText(_fromUtf8(""))
        self.uExternalAddId.setMaxLength(15)
        self.uExternalAddId.setObjectName(_fromUtf8("uExternalAddId"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.uExternalAddId)
        self.externalAddressIdSchemeLabel = QtGui.QLabel(NewAddressDialog)
        self.externalAddressIdSchemeLabel.setObjectName(_fromUtf8("externalAddressIdSchemeLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.externalAddressIdSchemeLabel)
        self.uExternalAddressIdScheme = QtGui.QLineEdit(NewAddressDialog)
        self.uExternalAddressIdScheme.setText(_fromUtf8(""))
        self.uExternalAddressIdScheme.setMaxLength(100)
        self.uExternalAddressIdScheme.setObjectName(_fromUtf8("uExternalAddressIdScheme"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.uExternalAddressIdScheme)
        self.lifeCycleLabel = QtGui.QLabel(NewAddressDialog)
        self.lifeCycleLabel.setObjectName(_fromUtf8("lifeCycleLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lifeCycleLabel)
        self.ulifeCycle = QtGui.QComboBox(NewAddressDialog)
        self.ulifeCycle.setObjectName(_fromUtf8("ulifeCycle"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.ulifeCycle)
        self.unitTypeLabel = QtGui.QLabel(NewAddressDialog)
        self.unitTypeLabel.setObjectName(_fromUtf8("unitTypeLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.unitTypeLabel)
        self.uUnitType = QtGui.QComboBox(NewAddressDialog)
        self.uUnitType.setObjectName(_fromUtf8("uUnitType"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.uUnitType)
        self.levelTypeLabel = QtGui.QLabel(NewAddressDialog)
        self.levelTypeLabel.setObjectName(_fromUtf8("levelTypeLabel"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.levelTypeLabel)
        self.uLevelType = QtGui.QComboBox(NewAddressDialog)
        self.uLevelType.setObjectName(_fromUtf8("uLevelType"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.uLevelType)
        self.levelValueLabel = QtGui.QLabel(NewAddressDialog)
        self.levelValueLabel.setObjectName(_fromUtf8("levelValueLabel"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.levelValueLabel)
        self.uLevelValue = QtGui.QLineEdit(NewAddressDialog)
        self.uLevelValue.setMaxLength(40)
        self.uLevelValue.setObjectName(_fromUtf8("uLevelValue"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.uLevelValue)
        self.line_4 = QtGui.QFrame(NewAddressDialog)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.SpanningRole, self.line_4)
        self.label_11 = QtGui.QLabel(NewAddressDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_11)
        self.roadCentrelineIdLabel = QtGui.QLabel(NewAddressDialog)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.roadCentrelineIdLabel.setFont(font)
        self.roadCentrelineIdLabel.setObjectName(_fromUtf8("roadCentrelineIdLabel"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.roadCentrelineIdLabel)
        self.roadPrefixLabel = QtGui.QLabel(NewAddressDialog)
        self.roadPrefixLabel.setObjectName(_fromUtf8("roadPrefixLabel"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.roadPrefixLabel)
        self.uRoadPrefix = QtGui.QLineEdit(NewAddressDialog)
        self.uRoadPrefix.setMaxLength(20)
        self.uRoadPrefix.setObjectName(_fromUtf8("uRoadPrefix"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.uRoadPrefix)
        self.roadNameLabel = QtGui.QLabel(NewAddressDialog)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.roadNameLabel.setFont(font)
        self.roadNameLabel.setObjectName(_fromUtf8("roadNameLabel"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.roadNameLabel)
        self.uRoadName = QtGui.QLineEdit(NewAddressDialog)
        self.uRoadName.setMaxLength(150)
        self.uRoadName.setObjectName(_fromUtf8("uRoadName"))
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.uRoadName)
        self.roadTypeNameLabel = QtGui.QLabel(NewAddressDialog)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.roadTypeNameLabel.setFont(font)
        self.roadTypeNameLabel.setObjectName(_fromUtf8("roadTypeNameLabel"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.roadTypeNameLabel)
        self.uRoadTypeName = QtGui.QLineEdit(NewAddressDialog)
        self.uRoadTypeName.setMaxLength(40)
        self.uRoadTypeName.setObjectName(_fromUtf8("uRoadTypeName"))
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.uRoadTypeName)
        self.roadSuffixLabel = QtGui.QLabel(NewAddressDialog)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.roadSuffixLabel.setFont(font)
        self.roadSuffixLabel.setObjectName(_fromUtf8("roadSuffixLabel"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.LabelRole, self.roadSuffixLabel)
        self.uRoadSuffix = QtGui.QLineEdit(NewAddressDialog)
        self.uRoadSuffix.setMaxLength(40)
        self.uRoadSuffix.setObjectName(_fromUtf8("uRoadSuffix"))
        self.formLayout.setWidget(13, QtGui.QFormLayout.FieldRole, self.uRoadSuffix)
        self.waterRouteNameLabel = QtGui.QLabel(NewAddressDialog)
        self.waterRouteNameLabel.setObjectName(_fromUtf8("waterRouteNameLabel"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.LabelRole, self.waterRouteNameLabel)
        self.uWaterRouteName = QtGui.QLineEdit(NewAddressDialog)
        self.uWaterRouteName.setMaxLength(100)
        self.uWaterRouteName.setObjectName(_fromUtf8("uWaterRouteName"))
        self.formLayout.setWidget(14, QtGui.QFormLayout.FieldRole, self.uWaterRouteName)
        self.waterNameLabel = QtGui.QLabel(NewAddressDialog)
        self.waterNameLabel.setObjectName(_fromUtf8("waterNameLabel"))
        self.formLayout.setWidget(15, QtGui.QFormLayout.LabelRole, self.waterNameLabel)
        self.uWaterName = QtGui.QLineEdit(NewAddressDialog)
        self.uWaterName.setMaxLength(100)
        self.uWaterName.setObjectName(_fromUtf8("uWaterName"))
        self.formLayout.setWidget(15, QtGui.QFormLayout.FieldRole, self.uWaterName)
        self.line_6 = QtGui.QFrame(NewAddressDialog)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.formLayout.setWidget(16, QtGui.QFormLayout.SpanningRole, self.line_6)
        self.label_10 = QtGui.QLabel(NewAddressDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(17, QtGui.QFormLayout.LabelRole, self.label_10)
        self.objectTypeLabel = QtGui.QLabel(NewAddressDialog)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.objectTypeLabel.setFont(font)
        self.objectTypeLabel.setObjectName(_fromUtf8("objectTypeLabel"))
        self.formLayout.setWidget(18, QtGui.QFormLayout.LabelRole, self.objectTypeLabel)
        self.UObjectType = QtGui.QComboBox(NewAddressDialog)
        self.UObjectType.setObjectName(_fromUtf8("UObjectType"))
        self.formLayout.setWidget(18, QtGui.QFormLayout.FieldRole, self.UObjectType)
        self.objectNameLabel = QtGui.QLabel(NewAddressDialog)
        self.objectNameLabel.setObjectName(_fromUtf8("objectNameLabel"))
        self.formLayout.setWidget(19, QtGui.QFormLayout.LabelRole, self.objectNameLabel)
        self.uObjectName = QtGui.QLineEdit(NewAddressDialog)
        self.uObjectName.setMaxLength(250)
        self.uObjectName.setObjectName(_fromUtf8("uObjectName"))
        self.formLayout.setWidget(19, QtGui.QFormLayout.FieldRole, self.uObjectName)
        self.externalObjectIdLabel = QtGui.QLabel(NewAddressDialog)
        self.externalObjectIdLabel.setObjectName(_fromUtf8("externalObjectIdLabel"))
        self.formLayout.setWidget(20, QtGui.QFormLayout.LabelRole, self.externalObjectIdLabel)
        self.uExternalObjectId = QtGui.QLineEdit(NewAddressDialog)
        self.uExternalObjectId.setMaxLength(15)
        self.uExternalObjectId.setObjectName(_fromUtf8("uExternalObjectId"))
        self.formLayout.setWidget(20, QtGui.QFormLayout.FieldRole, self.uExternalObjectId)
        self.extObjectIdSchemeLabel = QtGui.QLabel(NewAddressDialog)
        self.extObjectIdSchemeLabel.setObjectName(_fromUtf8("extObjectIdSchemeLabel"))
        self.formLayout.setWidget(21, QtGui.QFormLayout.LabelRole, self.extObjectIdSchemeLabel)
        self.uExtObjectIdScheme = QtGui.QLineEdit(NewAddressDialog)
        self.uExtObjectIdScheme.setMaxLength(100)
        self.uExtObjectIdScheme.setObjectName(_fromUtf8("uExtObjectIdScheme"))
        self.formLayout.setWidget(21, QtGui.QFormLayout.FieldRole, self.uExtObjectIdScheme)
        self.valuationReferenceLabel = QtGui.QLabel(NewAddressDialog)
        self.valuationReferenceLabel.setObjectName(_fromUtf8("valuationReferenceLabel"))
        self.formLayout.setWidget(22, QtGui.QFormLayout.LabelRole, self.valuationReferenceLabel)
        self.uValuationReference = QtGui.QLineEdit(NewAddressDialog)
        self.uValuationReference.setMaxLength(30)
        self.uValuationReference.setObjectName(_fromUtf8("uValuationReference"))
        self.formLayout.setWidget(22, QtGui.QFormLayout.FieldRole, self.uValuationReference)
        self.certificateOfTitleLabel = QtGui.QLabel(NewAddressDialog)
        self.certificateOfTitleLabel.setObjectName(_fromUtf8("certificateOfTitleLabel"))
        self.formLayout.setWidget(23, QtGui.QFormLayout.LabelRole, self.certificateOfTitleLabel)
        self.uCertificateOfTitle = QtGui.QLineEdit(NewAddressDialog)
        self.uCertificateOfTitle.setMaxLength(20)
        self.uCertificateOfTitle.setObjectName(_fromUtf8("uCertificateOfTitle"))
        self.formLayout.setWidget(23, QtGui.QFormLayout.FieldRole, self.uCertificateOfTitle)
        self.appellationLabel = QtGui.QLabel(NewAddressDialog)
        self.appellationLabel.setObjectName(_fromUtf8("appellationLabel"))
        self.formLayout.setWidget(24, QtGui.QFormLayout.LabelRole, self.appellationLabel)
        self.uAppellation = QtGui.QLineEdit(NewAddressDialog)
        self.uAppellation.setMaxLength(500)
        self.uAppellation.setObjectName(_fromUtf8("uAppellation"))
        self.formLayout.setWidget(24, QtGui.QFormLayout.FieldRole, self.uAppellation)
        self.uRoadCentrelineId = QtGui.QLineEdit(NewAddressDialog)
        self.uRoadCentrelineId.setObjectName(_fromUtf8("uRoadCentrelineId"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.uRoadCentrelineId)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.uAbort = QtGui.QPushButton(NewAddressDialog)
        self.uAbort.setObjectName(_fromUtf8("uAbort"))
        self.horizontalLayout.addWidget(self.uAbort)
        self.uSubmitAddressButton = QtGui.QPushButton(NewAddressDialog)
        self.uSubmitAddressButton.setObjectName(_fromUtf8("uSubmitAddressButton"))
        self.horizontalLayout.addWidget(self.uSubmitAddressButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(NewAddressDialog)
        QtCore.QMetaObject.connectSlotsByName(NewAddressDialog)
        NewAddressDialog.setTabOrder(self.uFullNum, self.uPrefix)
        NewAddressDialog.setTabOrder(self.uPrefix, self.uUnit)
        NewAddressDialog.setTabOrder(self.uUnit, self.uBase)
        NewAddressDialog.setTabOrder(self.uBase, self.uHigh)
        NewAddressDialog.setTabOrder(self.uHigh, self.uAlpha)
        NewAddressDialog.setTabOrder(self.uAlpha, self.uExternalAddId)
        NewAddressDialog.setTabOrder(self.uExternalAddId, self.uExternalAddressIdScheme)
        NewAddressDialog.setTabOrder(self.uExternalAddressIdScheme, self.ulifeCycle)
        NewAddressDialog.setTabOrder(self.ulifeCycle, self.uUnitType)
        NewAddressDialog.setTabOrder(self.uUnitType, self.uLevelType)
        NewAddressDialog.setTabOrder(self.uLevelType, self.uLevelValue)
        NewAddressDialog.setTabOrder(self.uLevelValue, self.uRoadCentrelineId)
        NewAddressDialog.setTabOrder(self.uRoadCentrelineId, self.uRoadPrefix)
        NewAddressDialog.setTabOrder(self.uRoadPrefix, self.uRoadName)
        NewAddressDialog.setTabOrder(self.uRoadName, self.uRoadTypeName)
        NewAddressDialog.setTabOrder(self.uRoadTypeName, self.uRoadSuffix)
        NewAddressDialog.setTabOrder(self.uRoadSuffix, self.uWaterRouteName)
        NewAddressDialog.setTabOrder(self.uWaterRouteName, self.uWaterName)
        NewAddressDialog.setTabOrder(self.uWaterName, self.UObjectType)
        NewAddressDialog.setTabOrder(self.UObjectType, self.uObjectName)
        NewAddressDialog.setTabOrder(self.uObjectName, self.uExternalObjectId)
        NewAddressDialog.setTabOrder(self.uExternalObjectId, self.uExtObjectIdScheme)
        NewAddressDialog.setTabOrder(self.uExtObjectIdScheme, self.uValuationReference)
        NewAddressDialog.setTabOrder(self.uValuationReference, self.uCertificateOfTitle)
        NewAddressDialog.setTabOrder(self.uCertificateOfTitle, self.uAppellation)
        NewAddressDialog.setTabOrder(self.uAppellation, self.uAbort)
        NewAddressDialog.setTabOrder(self.uAbort, self.uAddressType)

    def retranslateUi(self, NewAddressDialog):
        NewAddressDialog.setWindowTitle(QtGui.QApplication.translate("NewAddressDialog", "Create New Address", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("NewAddressDialog", "Full Number:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("NewAddressDialog", "Unit:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("NewAddressDialog", "Base:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("NewAddressDialog", "Alpha:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("NewAddressDialog", "Prefix:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("NewAddressDialog", "High:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("NewAddressDialog", "Address Extras:", None, QtGui.QApplication.UnicodeUTF8))
        self.externalAddressIdLabel.setText(QtGui.QApplication.translate("NewAddressDialog", "External Address Id:", None, QtGui.QApplication.UnicodeUTF8))
        self.externalAddressIdSchemeLabel.setText(QtGui.QApplication.translate("NewAddressDialog", "Ext Address Id Scheme:", None, QtGui.QApplication.UnicodeUTF8))
        self.lifeCycleLabel.setText(QtGui.QApplication.translate("NewAddressDialog", "Life Cycle:", None, QtGui.QApplication.UnicodeUTF8))
        self.unitTypeLabel.setText(QtGui.QApplication.translate("NewAddressDialog", "Unit Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.levelTypeLabel.setText(QtGui.QApplication.translate("NewAddressDialog", "Level Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.levelValueLabel.setText(QtGui.QApplication.translate("NewAddressDialog", "Level Value:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("NewAddressDialog", "Road:", None, QtGui.QApplication.UnicodeUTF8))
        self.roadCentrelineIdLabel.setText(QtGui.QApplication.translate("NewAddressDialog", "Road Centreline Id:", None, QtGui.QApplication.UnicodeUTF8))
        self.roadPrefixLabel.setText(QtGui.QApplication.translate("NewAddressDialog", "Road Prefix:", None, QtGui.QApplication.UnicodeUTF8))
        self.roadNameLabel.setText(QtGui.QApplication.translate("NewAddressDialog", "Road Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.roadTypeNameLabel.setText(QtGui.QApplication.translate("NewAddressDialog", "Road Type Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.roadSuffixLabel.setText(QtGui.QApplication.translate("NewAddressDialog", "Road Suffix:", None, QtGui.QApplication.UnicodeUTF8))
        self.waterRouteNameLabel.setText(QtGui.QApplication.translate("NewAddressDialog", "Water Route Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.waterNameLabel.setText(QtGui.QApplication.translate("NewAddressDialog", "Water Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("NewAddressDialog", "Addressable Object:", None, QtGui.QApplication.UnicodeUTF8))
        self.objectTypeLabel.setText(QtGui.QApplication.translate("NewAddressDialog", "Object Type", None, QtGui.QApplication.UnicodeUTF8))
        self.objectNameLabel.setText(QtGui.QApplication.translate("NewAddressDialog", "Object Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.externalObjectIdLabel.setText(QtGui.QApplication.translate("NewAddressDialog", "External Object Id:", None, QtGui.QApplication.UnicodeUTF8))
        self.extObjectIdSchemeLabel.setText(QtGui.QApplication.translate("NewAddressDialog", "Ext Object Id Scheme:", None, QtGui.QApplication.UnicodeUTF8))
        self.valuationReferenceLabel.setText(QtGui.QApplication.translate("NewAddressDialog", "Valuation Reference:", None, QtGui.QApplication.UnicodeUTF8))
        self.certificateOfTitleLabel.setText(QtGui.QApplication.translate("NewAddressDialog", "Certificate Of Title:", None, QtGui.QApplication.UnicodeUTF8))
        self.appellationLabel.setText(QtGui.QApplication.translate("NewAddressDialog", "Appellation:", None, QtGui.QApplication.UnicodeUTF8))
        self.uAbort.setText(QtGui.QApplication.translate("NewAddressDialog", "Abort", None, QtGui.QApplication.UnicodeUTF8))
        self.uSubmitAddressButton.setText(QtGui.QApplication.translate("NewAddressDialog", "Submit", None, QtGui.QApplication.UnicodeUTF8))

