# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AimsUI/AimsClient/Gui/Ui_QueueEditorWidget.ui'
#
# Created: Fri Sep 16 08:58:25 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_QueueEditorWidget(object):
    def setupUi(self, QueueEditorWidget):
        QueueEditorWidget.setObjectName(_fromUtf8("QueueEditorWidget"))
        QueueEditorWidget.resize(400, 952)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QueueEditorWidget.sizePolicy().hasHeightForWidth())
        QueueEditorWidget.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(QueueEditorWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrollArea = QtGui.QScrollArea(QueueEditorWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -6, 364, 1122))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter = QtGui.QSplitter(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.gridLayoutWidget_7 = QtGui.QWidget(self.splitter)
        self.gridLayoutWidget_7.setObjectName(_fromUtf8("gridLayoutWidget_7"))
        self.gridLayout_14 = QtGui.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_14.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout_14.setMargin(0)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.lNotes = QtGui.QLabel(self.gridLayoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lNotes.sizePolicy().hasHeightForWidth())
        self.lNotes.setSizePolicy(sizePolicy)
        self.lNotes.setMinimumSize(QtCore.QSize(0, 0))
        self.lNotes.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lNotes.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lNotes.setWordWrap(True)
        self.lNotes.setObjectName(_fromUtf8("lNotes"))
        self.gridLayout_14.addWidget(self.lNotes, 1, 0, 1, 1)
        self.scrollArea_2 = QtGui.QScrollArea(self.gridLayoutWidget_7)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 261, 76))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.uWarning = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uWarning.sizePolicy().hasHeightForWidth())
        self.uWarning.setSizePolicy(sizePolicy)
        self.uWarning.setText(_fromUtf8(""))
        self.uWarning.setWordWrap(True)
        self.uWarning.setObjectName(_fromUtf8("uWarning"))
        self.verticalLayout_4.addWidget(self.uWarning)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_14.addWidget(self.scrollArea_2, 0, 1, 1, 1)
        self.scrollArea_4 = QtGui.QScrollArea(self.gridLayoutWidget_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_4.sizePolicy().hasHeightForWidth())
        self.scrollArea_4.setSizePolicy(sizePolicy)
        self.scrollArea_4.setMaximumSize(QtCore.QSize(16777215, 40))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName(_fromUtf8("scrollArea_4"))
        self.scrollAreaWidgetContents_7 = QtGui.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 261, 38))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_7.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_7.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_7.setObjectName(_fromUtf8("scrollAreaWidgetContents_7"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_7)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.uNotes = QtGui.QLabel(self.scrollAreaWidgetContents_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uNotes.sizePolicy().hasHeightForWidth())
        self.uNotes.setSizePolicy(sizePolicy)
        self.uNotes.setText(_fromUtf8(""))
        self.uNotes.setWordWrap(True)
        self.uNotes.setObjectName(_fromUtf8("uNotes"))
        self.verticalLayout_7.addWidget(self.uNotes)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_7)
        self.gridLayout_14.addWidget(self.scrollArea_4, 1, 1, 1, 1)
        self.lWarning = QtGui.QLabel(self.gridLayoutWidget_7)
        self.lWarning.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lWarning.sizePolicy().hasHeightForWidth())
        self.lWarning.setSizePolicy(sizePolicy)
        self.lWarning.setMinimumSize(QtCore.QSize(0, 0))
        self.lWarning.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lWarning.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lWarning.setObjectName(_fromUtf8("lWarning"))
        self.gridLayout_14.addWidget(self.lWarning, 0, 0, 1, 1)
        self.gridLayoutWidget_8 = QtGui.QWidget(self.splitter)
        self.gridLayoutWidget_8.setObjectName(_fromUtf8("gridLayoutWidget_8"))
        self.gridLayout_15 = QtGui.QGridLayout(self.gridLayoutWidget_8)
        self.gridLayout_15.setMargin(0)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.lWaterRoute = QtGui.QLabel(self.gridLayoutWidget_8)
        self.lWaterRoute.setObjectName(_fromUtf8("lWaterRoute"))
        self.gridLayout_15.addWidget(self.lWaterRoute, 17, 0, 1, 1)
        self.lNumberPrefix = QtGui.QLabel(self.gridLayoutWidget_8)
        self.lNumberPrefix.setObjectName(_fromUtf8("lNumberPrefix"))
        self.gridLayout_15.addWidget(self.lNumberPrefix, 6, 0, 1, 1)
        self.uPrefix = QtGui.QLineEdit(self.gridLayoutWidget_8)
        self.uPrefix.setMinimumSize(QtCore.QSize(0, 0))
        self.uPrefix.setText(_fromUtf8(""))
        self.uPrefix.setObjectName(_fromUtf8("uPrefix"))
        self.gridLayout_15.addWidget(self.uPrefix, 6, 1, 1, 1)
        self.uUnitType = QtGui.QComboBox(self.gridLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uUnitType.sizePolicy().hasHeightForWidth())
        self.uUnitType.setSizePolicy(sizePolicy)
        self.uUnitType.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.uUnitType.setObjectName(_fromUtf8("uUnitType"))
        self.gridLayout_15.addWidget(self.uUnitType, 4, 1, 1, 1)
        self.lLevelType = QtGui.QLabel(self.gridLayoutWidget_8)
        self.lLevelType.setObjectName(_fromUtf8("lLevelType"))
        self.gridLayout_15.addWidget(self.lLevelType, 2, 0, 1, 1)
        self.lBaseNumber = QtGui.QLabel(self.gridLayoutWidget_8)
        self.lBaseNumber.setObjectName(_fromUtf8("lBaseNumber"))
        self.gridLayout_15.addWidget(self.lBaseNumber, 7, 0, 1, 1)
        self.uRoadPrefix = QtGui.QLineEdit(self.gridLayoutWidget_8)
        self.uRoadPrefix.setText(_fromUtf8(""))
        self.uRoadPrefix.setReadOnly(True)
        self.uRoadPrefix.setObjectName(_fromUtf8("uRoadPrefix"))
        self.gridLayout_15.addWidget(self.uRoadPrefix, 13, 1, 1, 1)
        self.uAlpha = QtGui.QLineEdit(self.gridLayoutWidget_8)
        self.uAlpha.setMinimumSize(QtCore.QSize(0, 0))
        self.uAlpha.setText(_fromUtf8(""))
        self.uAlpha.setObjectName(_fromUtf8("uAlpha"))
        self.gridLayout_15.addWidget(self.uAlpha, 8, 1, 1, 1)
        self.uWaterRouteName = QtGui.QLineEdit(self.gridLayoutWidget_8)
        self.uWaterRouteName.setText(_fromUtf8(""))
        self.uWaterRouteName.setReadOnly(True)
        self.uWaterRouteName.setObjectName(_fromUtf8("uWaterRouteName"))
        self.gridLayout_15.addWidget(self.uWaterRouteName, 17, 1, 1, 1)
        self.lNumberHigh = QtGui.QLabel(self.gridLayoutWidget_8)
        self.lNumberHigh.setObjectName(_fromUtf8("lNumberHigh"))
        self.gridLayout_15.addWidget(self.lNumberHigh, 9, 0, 1, 1)
        self.lLevelValue = QtGui.QLabel(self.gridLayoutWidget_8)
        self.lLevelValue.setObjectName(_fromUtf8("lLevelValue"))
        self.gridLayout_15.addWidget(self.lLevelValue, 3, 0, 1, 1)
        self.lAddressType = QtGui.QLabel(self.gridLayoutWidget_8)
        self.lAddressType.setMaximumSize(QtCore.QSize(175, 16777215))
        self.lAddressType.setObjectName(_fromUtf8("lAddressType"))
        self.gridLayout_15.addWidget(self.lAddressType, 0, 0, 1, 1)
        self.lRoadType = QtGui.QLabel(self.gridLayoutWidget_8)
        self.lRoadType.setObjectName(_fromUtf8("lRoadType"))
        self.gridLayout_15.addWidget(self.lRoadType, 15, 0, 1, 1)
        self.uRoadSuffix = QtGui.QLineEdit(self.gridLayoutWidget_8)
        self.uRoadSuffix.setText(_fromUtf8(""))
        self.uRoadSuffix.setReadOnly(True)
        self.uRoadSuffix.setObjectName(_fromUtf8("uRoadSuffix"))
        self.gridLayout_15.addWidget(self.uRoadSuffix, 16, 1, 1, 1)
        self.uRoadName = QtGui.QLineEdit(self.gridLayoutWidget_8)
        self.uRoadName.setText(_fromUtf8(""))
        self.uRoadName.setReadOnly(True)
        self.uRoadName.setObjectName(_fromUtf8("uRoadName"))
        self.gridLayout_15.addWidget(self.uRoadName, 14, 1, 1, 1)
        self.uLevelValue = QtGui.QLineEdit(self.gridLayoutWidget_8)
        self.uLevelValue.setMinimumSize(QtCore.QSize(0, 0))
        self.uLevelValue.setText(_fromUtf8(""))
        self.uLevelValue.setObjectName(_fromUtf8("uLevelValue"))
        self.gridLayout_15.addWidget(self.uLevelValue, 3, 1, 1, 1)
        self.lRoadPrefix = QtGui.QLabel(self.gridLayoutWidget_8)
        self.lRoadPrefix.setMaximumSize(QtCore.QSize(175, 16777215))
        self.lRoadPrefix.setObjectName(_fromUtf8("lRoadPrefix"))
        self.gridLayout_15.addWidget(self.lRoadPrefix, 13, 0, 1, 1)
        self.lAplha = QtGui.QLabel(self.gridLayoutWidget_8)
        self.lAplha.setObjectName(_fromUtf8("lAplha"))
        self.gridLayout_15.addWidget(self.lAplha, 8, 0, 1, 1)
        self.uUnit = QtGui.QLineEdit(self.gridLayoutWidget_8)
        self.uUnit.setMinimumSize(QtCore.QSize(0, 0))
        self.uUnit.setText(_fromUtf8(""))
        self.uUnit.setObjectName(_fromUtf8("uUnit"))
        self.gridLayout_15.addWidget(self.uUnit, 5, 1, 1, 1)
        self.lUnitValue = QtGui.QLabel(self.gridLayoutWidget_8)
        self.lUnitValue.setMaximumSize(QtCore.QSize(175, 16777215))
        self.lUnitValue.setObjectName(_fromUtf8("lUnitValue"))
        self.gridLayout_15.addWidget(self.lUnitValue, 5, 0, 1, 1)
        self.uLevelType = QtGui.QComboBox(self.gridLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uLevelType.sizePolicy().hasHeightForWidth())
        self.uLevelType.setSizePolicy(sizePolicy)
        self.uLevelType.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.uLevelType.setObjectName(_fromUtf8("uLevelType"))
        self.gridLayout_15.addWidget(self.uLevelType, 2, 1, 1, 1)
        self.lWaterName = QtGui.QLabel(self.gridLayoutWidget_8)
        self.lWaterName.setObjectName(_fromUtf8("lWaterName"))
        self.gridLayout_15.addWidget(self.lWaterName, 18, 0, 1, 1)
        self.uBase = QtGui.QLineEdit(self.gridLayoutWidget_8)
        self.uBase.setMinimumSize(QtCore.QSize(0, 0))
        self.uBase.setText(_fromUtf8(""))
        self.uBase.setObjectName(_fromUtf8("uBase"))
        self.gridLayout_15.addWidget(self.uBase, 7, 1, 1, 1)
        self.uHigh = QtGui.QLineEdit(self.gridLayoutWidget_8)
        self.uHigh.setMinimumSize(QtCore.QSize(0, 0))
        self.uHigh.setText(_fromUtf8(""))
        self.uHigh.setObjectName(_fromUtf8("uHigh"))
        self.gridLayout_15.addWidget(self.uHigh, 9, 1, 1, 1)
        self.lRclId = QtGui.QLabel(self.gridLayoutWidget_8)
        self.lRclId.setObjectName(_fromUtf8("lRclId"))
        self.gridLayout_15.addWidget(self.lRclId, 12, 0, 1, 1)
        self.lRoadSuffix = QtGui.QLabel(self.gridLayoutWidget_8)
        self.lRoadSuffix.setObjectName(_fromUtf8("lRoadSuffix"))
        self.gridLayout_15.addWidget(self.lRoadSuffix, 16, 0, 1, 1)
        self.lRoadName = QtGui.QLabel(self.gridLayoutWidget_8)
        self.lRoadName.setMaximumSize(QtCore.QSize(175, 16777215))
        self.lRoadName.setObjectName(_fromUtf8("lRoadName"))
        self.gridLayout_15.addWidget(self.lRoadName, 14, 0, 1, 1)
        self.uAddressType = QtGui.QComboBox(self.gridLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uAddressType.sizePolicy().hasHeightForWidth())
        self.uAddressType.setSizePolicy(sizePolicy)
        self.uAddressType.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.uAddressType.setObjectName(_fromUtf8("uAddressType"))
        self.gridLayout_15.addWidget(self.uAddressType, 0, 1, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.uRclId = QtGui.QLineEdit(self.gridLayoutWidget_8)
        self.uRclId.setReadOnly(True)
        self.uRclId.setObjectName(_fromUtf8("uRclId"))
        self.horizontalLayout.addWidget(self.uRclId)
        self.uGetRclToolButton = QtGui.QToolButton(self.gridLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uGetRclToolButton.sizePolicy().hasHeightForWidth())
        self.uGetRclToolButton.setSizePolicy(sizePolicy)
        self.uGetRclToolButton.setMinimumSize(QtCore.QSize(0, 0))
        self.uGetRclToolButton.setMaximumSize(QtCore.QSize(24, 16777215))
        self.uGetRclToolButton.setText(_fromUtf8(""))
        self.uGetRclToolButton.setObjectName(_fromUtf8("uGetRclToolButton"))
        self.horizontalLayout.addWidget(self.uGetRclToolButton)
        self.gridLayout_15.addLayout(self.horizontalLayout, 12, 1, 1, 1)
        self.uExternalAddId = QtGui.QLineEdit(self.gridLayoutWidget_8)
        self.uExternalAddId.setMaxLength(15)
        self.uExternalAddId.setObjectName(_fromUtf8("uExternalAddId"))
        self.gridLayout_15.addWidget(self.uExternalAddId, 11, 1, 1, 1)
        self.lExtAddIdScheme = QtGui.QLabel(self.gridLayoutWidget_8)
        self.lExtAddIdScheme.setObjectName(_fromUtf8("lExtAddIdScheme"))
        self.gridLayout_15.addWidget(self.lExtAddIdScheme, 10, 0, 1, 1)
        self.uExternalAddressIdScheme = QtGui.QLineEdit(self.gridLayoutWidget_8)
        self.uExternalAddressIdScheme.setText(_fromUtf8(""))
        self.uExternalAddressIdScheme.setObjectName(_fromUtf8("uExternalAddressIdScheme"))
        self.gridLayout_15.addWidget(self.uExternalAddressIdScheme, 10, 1, 1, 1)
        self.lExtAddId = QtGui.QLabel(self.gridLayoutWidget_8)
        self.lExtAddId.setObjectName(_fromUtf8("lExtAddId"))
        self.gridLayout_15.addWidget(self.lExtAddId, 11, 0, 1, 1)
        self.uRoadTypeName = QtGui.QLineEdit(self.gridLayoutWidget_8)
        self.uRoadTypeName.setText(_fromUtf8(""))
        self.uRoadTypeName.setReadOnly(True)
        self.uRoadTypeName.setObjectName(_fromUtf8("uRoadTypeName"))
        self.gridLayout_15.addWidget(self.uRoadTypeName, 15, 1, 1, 1)
        self.uWaterName = QtGui.QLineEdit(self.gridLayoutWidget_8)
        self.uWaterName.setText(_fromUtf8(""))
        self.uWaterName.setReadOnly(True)
        self.uWaterName.setObjectName(_fromUtf8("uWaterName"))
        self.gridLayout_15.addWidget(self.uWaterName, 18, 1, 1, 1)
        self.ulifeCycle = QtGui.QComboBox(self.gridLayoutWidget_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ulifeCycle.sizePolicy().hasHeightForWidth())
        self.ulifeCycle.setSizePolicy(sizePolicy)
        self.ulifeCycle.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.ulifeCycle.setObjectName(_fromUtf8("ulifeCycle"))
        self.gridLayout_15.addWidget(self.ulifeCycle, 1, 1, 1, 1)
        self.lLifeCycle = QtGui.QLabel(self.gridLayoutWidget_8)
        self.lLifeCycle.setObjectName(_fromUtf8("lLifeCycle"))
        self.gridLayout_15.addWidget(self.lLifeCycle, 1, 0, 1, 1)
        self.lUnitType = QtGui.QLabel(self.gridLayoutWidget_8)
        self.lUnitType.setMaximumSize(QtCore.QSize(175, 16777215))
        self.lUnitType.setObjectName(_fromUtf8("lUnitType"))
        self.gridLayout_15.addWidget(self.lUnitType, 4, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.splitter)
        self.line = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.label_121 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_121.sizePolicy().hasHeightForWidth())
        self.label_121.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_121.setFont(font)
        self.label_121.setObjectName(_fromUtf8("label_121"))
        self.verticalLayout_2.addWidget(self.label_121)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.lPositionType = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lPositionType.setObjectName(_fromUtf8("lPositionType"))
        self.gridLayout_13.addWidget(self.lPositionType, 2, 0, 1, 1)
        self.uObjectType = QtGui.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uObjectType.sizePolicy().hasHeightForWidth())
        self.uObjectType.setSizePolicy(sizePolicy)
        self.uObjectType.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.uObjectType.setObjectName(_fromUtf8("uObjectType"))
        self.gridLayout_13.addWidget(self.uObjectType, 0, 1, 1, 1)
        self.uObjectName = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.uObjectName.setText(_fromUtf8(""))
        self.uObjectName.setObjectName(_fromUtf8("uObjectName"))
        self.gridLayout_13.addWidget(self.uObjectName, 1, 1, 1, 1)
        self.lExternalObjectId = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lExternalObjectId.setObjectName(_fromUtf8("lExternalObjectId"))
        self.gridLayout_13.addWidget(self.lExternalObjectId, 4, 0, 1, 1)
        self.lExtObjectIdScheme = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lExtObjectIdScheme.setObjectName(_fromUtf8("lExtObjectIdScheme"))
        self.gridLayout_13.addWidget(self.lExtObjectIdScheme, 3, 0, 1, 1)
        self.lMblk = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lMblk.setObjectName(_fromUtf8("lMblk"))
        self.gridLayout_13.addWidget(self.lMblk, 8, 0, 1, 1)
        self.uAppellation = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.uAppellation.setText(_fromUtf8(""))
        self.uAppellation.setObjectName(_fromUtf8("uAppellation"))
        self.gridLayout_13.addWidget(self.uAppellation, 7, 1, 1, 1)
        self.lAppellation = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lAppellation.setObjectName(_fromUtf8("lAppellation"))
        self.gridLayout_13.addWidget(self.lAppellation, 7, 0, 1, 1)
        self.lValref = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lValref.setObjectName(_fromUtf8("lValref"))
        self.gridLayout_13.addWidget(self.lValref, 5, 0, 1, 1)
        self.uExtObjectIdScheme = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.uExtObjectIdScheme.setObjectName(_fromUtf8("uExtObjectIdScheme"))
        self.gridLayout_13.addWidget(self.uExtObjectIdScheme, 3, 1, 1, 1)
        self.lCertTitle = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lCertTitle.setObjectName(_fromUtf8("lCertTitle"))
        self.gridLayout_13.addWidget(self.lCertTitle, 6, 0, 1, 1)
        self.uExternalObjectId = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.uExternalObjectId.setText(_fromUtf8(""))
        self.uExternalObjectId.setObjectName(_fromUtf8("uExternalObjectId"))
        self.gridLayout_13.addWidget(self.uExternalObjectId, 4, 1, 1, 1)
        self.uValuationReference = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.uValuationReference.setText(_fromUtf8(""))
        self.uValuationReference.setObjectName(_fromUtf8("uValuationReference"))
        self.gridLayout_13.addWidget(self.uValuationReference, 5, 1, 1, 1)
        self.lObjType = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lObjType.setMinimumSize(QtCore.QSize(130, 0))
        self.lObjType.setObjectName(_fromUtf8("lObjType"))
        self.gridLayout_13.addWidget(self.lObjType, 0, 0, 1, 1)
        self.uMblkOverride = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.uMblkOverride.setMaxLength(7)
        self.uMblkOverride.setObjectName(_fromUtf8("uMblkOverride"))
        self.gridLayout_13.addWidget(self.uMblkOverride, 8, 1, 1, 1)
        self.uCertificateOfTitle = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.uCertificateOfTitle.setText(_fromUtf8(""))
        self.uCertificateOfTitle.setObjectName(_fromUtf8("uCertificateOfTitle"))
        self.gridLayout_13.addWidget(self.uCertificateOfTitle, 6, 1, 1, 1)
        self.lObjName = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.lObjName.setObjectName(_fromUtf8("lObjName"))
        self.gridLayout_13.addWidget(self.lObjName, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.uPositionType = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.uPositionType.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.uPositionType.setObjectName(_fromUtf8("uPositionType"))
        self.horizontalLayout_3.addWidget(self.uPositionType)
        self.uUpdatePosButton = QtGui.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uUpdatePosButton.sizePolicy().hasHeightForWidth())
        self.uUpdatePosButton.setSizePolicy(sizePolicy)
        self.uUpdatePosButton.setMinimumSize(QtCore.QSize(24, 0))
        self.uUpdatePosButton.setMaximumSize(QtCore.QSize(24, 16777215))
        self.uUpdatePosButton.setText(_fromUtf8(""))
        self.uUpdatePosButton.setObjectName(_fromUtf8("uUpdatePosButton"))
        self.horizontalLayout_3.addWidget(self.uUpdatePosButton)
        self.gridLayout_13.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_13)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(QueueEditorWidget)
        QtCore.QMetaObject.connectSlotsByName(QueueEditorWidget)
        QueueEditorWidget.setTabOrder(self.uAddressType, self.ulifeCycle)
        QueueEditorWidget.setTabOrder(self.ulifeCycle, self.uLevelType)
        QueueEditorWidget.setTabOrder(self.uLevelType, self.uLevelValue)
        QueueEditorWidget.setTabOrder(self.uLevelValue, self.uUnitType)
        QueueEditorWidget.setTabOrder(self.uUnitType, self.uUnit)
        QueueEditorWidget.setTabOrder(self.uUnit, self.uPrefix)
        QueueEditorWidget.setTabOrder(self.uPrefix, self.uBase)
        QueueEditorWidget.setTabOrder(self.uBase, self.uAlpha)
        QueueEditorWidget.setTabOrder(self.uAlpha, self.uHigh)
        QueueEditorWidget.setTabOrder(self.uHigh, self.uExternalAddressIdScheme)
        QueueEditorWidget.setTabOrder(self.uExternalAddressIdScheme, self.uExternalAddId)
        QueueEditorWidget.setTabOrder(self.uExternalAddId, self.uRclId)
        QueueEditorWidget.setTabOrder(self.uRclId, self.uRoadPrefix)
        QueueEditorWidget.setTabOrder(self.uRoadPrefix, self.uRoadName)
        QueueEditorWidget.setTabOrder(self.uRoadName, self.uRoadTypeName)
        QueueEditorWidget.setTabOrder(self.uRoadTypeName, self.uRoadSuffix)
        QueueEditorWidget.setTabOrder(self.uRoadSuffix, self.uWaterRouteName)
        QueueEditorWidget.setTabOrder(self.uWaterRouteName, self.uWaterName)
        QueueEditorWidget.setTabOrder(self.uWaterName, self.uObjectType)
        QueueEditorWidget.setTabOrder(self.uObjectType, self.uObjectName)
        QueueEditorWidget.setTabOrder(self.uObjectName, self.uExtObjectIdScheme)
        QueueEditorWidget.setTabOrder(self.uExtObjectIdScheme, self.uExternalObjectId)
        QueueEditorWidget.setTabOrder(self.uExternalObjectId, self.uValuationReference)
        QueueEditorWidget.setTabOrder(self.uValuationReference, self.uCertificateOfTitle)
        QueueEditorWidget.setTabOrder(self.uCertificateOfTitle, self.uAppellation)
        QueueEditorWidget.setTabOrder(self.uAppellation, self.uMblkOverride)
        QueueEditorWidget.setTabOrder(self.uMblkOverride, self.uGetRclToolButton)
        QueueEditorWidget.setTabOrder(self.uGetRclToolButton, self.scrollArea_2)
        QueueEditorWidget.setTabOrder(self.scrollArea_2, self.scrollArea)
        QueueEditorWidget.setTabOrder(self.scrollArea, self.scrollArea_4)

    def retranslateUi(self, QueueEditorWidget):
        QueueEditorWidget.setWindowTitle(_translate("QueueEditorWidget", "Form", None))
        self.lNotes.setText(_translate("QueueEditorWidget", "Source Notes:", None))
        self.lWarning.setText(_translate("QueueEditorWidget", "Warnings:", None))
        self.lWaterRoute.setText(_translate("QueueEditorWidget", "Water Route:", None))
        self.lNumberPrefix.setText(_translate("QueueEditorWidget", "Number Prefix:", None))
        self.lLevelType.setText(_translate("QueueEditorWidget", "Level Type:", None))
        self.lBaseNumber.setText(_translate("QueueEditorWidget", "Base Number:", None))
        self.lNumberHigh.setText(_translate("QueueEditorWidget", "Number High:", None))
        self.lLevelValue.setText(_translate("QueueEditorWidget", "Level Value:", None))
        self.lAddressType.setText(_translate("QueueEditorWidget", "Address Type:", None))
        self.lRoadType.setText(_translate("QueueEditorWidget", "Road Type:", None))
        self.lRoadPrefix.setText(_translate("QueueEditorWidget", "Road Prefix:", None))
        self.lAplha.setText(_translate("QueueEditorWidget", "Alpha:", None))
        self.lUnitValue.setText(_translate("QueueEditorWidget", "Unit Value:", None))
        self.lWaterName.setText(_translate("QueueEditorWidget", "Water Name:", None))
        self.lRclId.setText(_translate("QueueEditorWidget", "RCL Id:", None))
        self.lRoadSuffix.setText(_translate("QueueEditorWidget", "Road Suffix:", None))
        self.lRoadName.setText(_translate("QueueEditorWidget", "Road Name:", None))
        self.lExtAddIdScheme.setText(_translate("QueueEditorWidget", "Ext. Add  Id Scheme:", None))
        self.lExtAddId.setText(_translate("QueueEditorWidget", "Ext. Add  Id:", None))
        self.lLifeCycle.setText(_translate("QueueEditorWidget", "Lifecycle:", None))
        self.lUnitType.setText(_translate("QueueEditorWidget", "Unit Type:", None))
        self.label_121.setText(_translate("QueueEditorWidget", "Addressable Object:", None))
        self.lPositionType.setText(_translate("QueueEditorWidget", "Position Type:", None))
        self.lExternalObjectId.setText(_translate("QueueEditorWidget", "Ext. Obj Id:", None))
        self.lExtObjectIdScheme.setText(_translate("QueueEditorWidget", "Ext. Obj Id Scheme:", None))
        self.lMblk.setText(_translate("QueueEditorWidget", "Mblk Override:", None))
        self.lAppellation.setText(_translate("QueueEditorWidget", "Appellation:", None))
        self.lValref.setText(_translate("QueueEditorWidget", "Val Ref:", None))
        self.lCertTitle.setText(_translate("QueueEditorWidget", "Cert. of Title:", None))
        self.lObjType.setText(_translate("QueueEditorWidget", "Object Type:", None))
        self.lObjName.setText(_translate("QueueEditorWidget", "Object Name:", None))

