# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ComfirmSelection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ComfirmSelection(object):
    def setupUi(self, ComfirmSelection):
        ComfirmSelection.setObjectName("ComfirmSelection")
        ComfirmSelection.resize(621, 270)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ComfirmSelection)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(ComfirmSelection)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.uSadListView = DictionaryListView(ComfirmSelection)
        self.uSadListView.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.uSadListView.setObjectName("uSadListView")
        self.verticalLayout_2.addWidget(self.uSadListView)
        self.buttonBox = QtWidgets.QDialogButtonBox(ComfirmSelection)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(ComfirmSelection)
        self.buttonBox.accepted.connect(ComfirmSelection.accept)
        self.buttonBox.rejected.connect(ComfirmSelection.reject)
        QtCore.QMetaObject.connectSlotsByName(ComfirmSelection)

    def retranslateUi(self, ComfirmSelection):
        _translate = QtCore.QCoreApplication.translate
        ComfirmSelection.setWindowTitle(_translate("ComfirmSelection", "Select feature to update"))
        self.label_2.setText(_translate("ComfirmSelection", "Please Confirm Your Selection:"))
from AimsUI.AimsClient.Gui.DictionaryList import DictionaryListView


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ComfirmSelection = QtWidgets.QDialog()
    ui = Ui_ComfirmSelection()
    ui.setupUi(ComfirmSelection)
    ComfirmSelection.show()
    sys.exit(app.exec_())
