name: Run Tests

on:
  push:
    branches:
      - master
      - HG-Aims-Upgrade

jobs:

  test:
    name: Test - QGIS ${{ matrix.qgis_image.name }} & Postgre ${{ matrix.db_image.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        qgis_image: 
          - {name: "3.28", image: "qgis/qgis:release-3_28"}
        db_image:
          - {name: "14-3.1", image: "kartoza/postgis:14-3.1"}
    
    env:
      PGHOST: localhost
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      BASE_DIR: ${{ github.workspace }}
      DB_DOCKER_IMAGE: ${{ matrix.db_image.image }}
      QGIS_DOCKER_IMAGE: ${{ matrix.qgis_image.image }}
      QGIS_DISPLAY: ":99"
      DOCKER_NETWORK: aims
      PLUGIN_NAME: QGIS-AIMS-Plugin
      
    steps:

        - name: Checkout QGIS-AIMS-Plugin
          uses: actions/checkout@v3

        - name: Create Docker Network
          run: bash $BASE_DIR/scripts/steps/create_docker_network.sh

        - name: Launch database container
          run: bash $BASE_DIR/scripts/steps/launch_database_container.sh

        - name: Run database tests
          run: bash $BASE_DIR/scripts/steps/run_db_tests.sh

        - name: Launch QGIS container
          run: bash $BASE_DIR/scripts/steps/launch_qgis_container.sh

        # - name: Load test data
        #   run: bash $BASE_DIR/scripts/steps/load_qgis_test_data.sh

        - name: Setup QGIS plugin
          run: bash $BASE_DIR/scripts/steps/setup_qgis_plugin.sh

        - name: Run QGIS tests
          run: bash $BASE_DIR/scripts/steps/run_qgis_tests.sh