name: Run Tests

on:
  push:
    branches:
      - master
      - HG-Aims-Upgrade
    # workflow_dispatch:


env:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  PLUGIN_NAME: QGIS-AIMS-Plugin
  PLUGIN_PATH: '..'
  TEST_RUN_FUNCTION: QGIS-AIMS-Plugin.Test.run_tests.run_test_modules

jobs:

  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_tags: [release-3_28]

    services:
      postgres:
        image: kartoza/postgis:14-3.1
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: aims_ci_test
        ports:
            - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        
    steps:

        - name: Checkout QGIS-AIMS-Plugin
          uses: actions/checkout@v3
          with:
            path: 'QGIS-AIMS-Plugin'

        # - name: Extract branch name
        #   shell: bash
        #   run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        #   id: extract_branch

        # - name: Print Github Branch Info
        #   shell: bash
        #   run: |
        #     cd $GITHUB_WORKSPACE
        #     echo "GitHub Branch: ${{ steps.extract_branch.outputs.branch }}"
        
        - name: Docker Pull and Run Matrix Image
          shell: bash
          run: |
            docker pull qgis/qgis:${{ matrix.docker_tags }}
            docker run -d --name qgis-testing-environment -v "${GITHUB_WORKSPACE}/${PLUGIN_PATH}":/tests_directory -e DISPLAY=:99 qgis/qgis:${{ matrix.docker_tags }}

        - name: Docker set up QGIS
          run: |
            docker exec qgis-testing-environment sh -c "qgis_setup.sh $PLUGIN_NAME"
            docker exec qgis-testing-environment sh -c "rm -f /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/$PLUGIN_NAME"
            docker exec qgis-testing-environment sh -c "ln -s /tests_directory/$PLUGIN_NAME /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/$PLUGIN_NAME"

        - name: Run tests
          shell: bash
          run: |
            docker exec qgis-testing-environment sh -c "qgis_testrunner.sh $TESTS_RUN_FUNCTION"
      