name: Run Tests

on:
    push:
      branches:
        - master
        - HG-Aims-Upgrade
    # workflow_dispatch:

jobs:

    test:

        runs-on: ubuntu-latest
        container: qgis/qgis:release-3_28

        services:
          postgres:
            image: kartoza/postgis:14-3.1
            env:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres
              POSTGRES_DB: aims_ci_test
            ports:
                - 5432:5432
            options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

        steps:

            - name: Checkout QGIS-AIMS-Plugin
              uses: actions/checkout@v3
              with:
                path: ''

            - name: Initialise QGIS
              shell: bash
              run: |
                cd $GITHUB_WORKSPACE/Test
                python3 qgis_docker_init.py

            - name: Run Python Tests
              shell: bash
              run: |
                cd $GITHUB_WORKSPACE
                python3 -m unittest discover -s $GITHUB_WORKSPACE/Test -p '*_Test.py'
                echo "Ran python tests"

         